repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: Lint with ruff.
        language: system
        files: ^mosquitto-consumer/src
        entry: uvx
        args: ["ruff", "check"]
        types: [python]
      - id: pyrefly
        name: pyrefly
        description: Type check with pryefly.
        language: system
        files: ^mosquitto-consumer/src
        entry: uvx
        args: ["pyrefly", "check"]
        types: [python]
      # - id: pytest
      #   name: pytest
      #   description: Run tests with pytest.
      #   language: system
      #   files: ^mosquitto-consumer/src
      #   entry: uvx
      #   args: ["pytest"]
      #   pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      name: trailing-whitespace
      description: Trim trailing whitespace.
    - id: end-of-file-fixer
      name: end-of-file-fixer
      description: Ensure files end with exactly one newline.
