services:
  broker:
    container_name: broker
    build: ./broker
    environment:
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    ports:
      - "1883:1883"
    volumes:
      - ./broker/config:/mosquitto/config:rw
      - ./broker/log:/mosquitto/log
      - mosquitto-data:/mosquitto/data
    restart: unless-stopped

  database:
    image: postgres:17.5
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_SUPER_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  consumer:
    container_name: consumer
    build: ./consumer
    environment:
      POSTGRES_DB_HOST: database
      MQTT_BROKER_HOST: broker
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SUPER_USER: ${POSTGRES_SUPER_USERNAME}
      POSTGRES_SUPER_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
    volumes:
      - ./consumer/logs:/app/logs
    depends_on:
      - database
      - broker
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway" # localhost

volumes:
  postgres-data:
  mosquitto-data:
