services:
  broker:
    container_name: broker
    build: ./broker
    secrets:
      - mqtt_username
      - mqtt_password
    ports:
      - "1883:1883"
    volumes:
      - ./broker/config:/mosquitto/config:rw
      - ./broker/log:/mosquitto/log
      - mosquitto-data:/mosquitto/data
    restart: unless-stopped

  database:
    image: postgres:17.5
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER_FILE: /run/secrets/postgres_super_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_super_password
    secrets:
      - postgres_super_username
      - postgres_super_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  consumer:
    container_name: consumer
    build:
      context: ./conduit
      args:
        PACKAGE_NAME: "consumer"
    environment:
      MQTT_HOST: broker
    secrets:
      - postgres_database_url
      - mqtt_username
      - mqtt_password
    depends_on:
      - database
      - broker
    restart: unless-stopped

volumes:
  postgres-data:
  mosquitto-data:

secrets:
  mqtt_username:
    file: ./secrets/mqtt_username
  mqtt_password:
    file: ./secrets/mqtt_password
  postgres_super_password:
    file: ./secrets/postgres_super_password
  postgres_super_username:
    file: ./secrets/postgres_super_username
  postgres_database_url:
    file: ./secrets/postgres_database_url
