[package]
name = "consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
shared = { version = "0.1.0", path = "../shared" }
sqlx = { workspace = true }
tokio = { workspace = true }
