name: Rust Check

defaults:
  run:
    working-directory: ./conduit

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./conduit
      - run: cargo clippy --all-targets --all-features -- -D warnings

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo install --force cargo-audit
      - run: cargo audit

  machete:
    name: Machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bnjbvr/cargo-machete@main

  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: plant_telemetry_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/plant_telemetry_test
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./conduit
      - run: cargo test
