name: Pyrefly Typechecking

on:
  push:
    branches: ["**"]

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['./mosquitto-consumer']
    defaults:
      run:
        working-directory: ./${{ matrix.directory }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Typecheck
      run: |
        uv run pyrefly check .
